services:
  - type: worker
    name: shuvo-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 run.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CONTROLLER_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: OWNER_ID
        sync: false
      - key: REQUIRED_GROUP
        sync: false
      - key: NASA_API_KEY
        value: DEMO_KEY
      - key: GROQ_API_KEY
        value: no-key-needed
      - key: GROQ_MODEL
        value: openai-fast
      - key: GROQ_API_BASE
        value: https://text.pollinations.ai/openai
      - key: POLLINATIONS_BASE
        value: https://image.pollinations.ai/prompt
    autoDeploy: true
